const fs = require('fs');
const path = require('path');

const pagesDir = path.join(__dirname, 'frontend', 'src', 'pages');

const fileReplacements = {
  "Dashboard.js": [
    // Imports & Hook
    ["import api from '../api';", "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';"],
    ["const Dashboard = () => {", "const Dashboard = () => {\n  const { t } = useTranslation();"],
    // Header & Export
    ["Carbon Footprint Analytics", "{t('dashboard.analyticsTitle')}"],
    ["Advanced real-time tracking, benchmarking comparisons, and personalized sustainability tips.", "{t('dashboard.analyticsSubtitle')}"],
    ["Export CSV", "{t('dashboard.exportCSV')}"],
    ["Export PDF", "{t('dashboard.exportPDF')}"],
    // Alerts
    ["Sign In Again", "{t('dashboard.signInAgain')}"],
    ["{error} Your session token may have expired. Please re-authenticate to load your live analytics data.", "{error} {t('dashboard.sessionExpiredAlert')}"],
    // Filters
    ["label=\"Select Date Range Filter\"", "label={t('dashboard.selectDateRangeFilter')}"],
    ["<MenuItem value=\"today\">Today</MenuItem>", "<MenuItem value=\"today\">{t('dashboard.presetToday')}</MenuItem>"],
    ["<MenuItem value=\"yesterday\">Yesterday</MenuItem>", "<MenuItem value=\"yesterday\">{t('dashboard.presetYesterday')}</MenuItem>"],
    ["<MenuItem value=\"last-7\">Last 7 Days</MenuItem>", "<MenuItem value=\"last-7\">{t('dashboard.presetLast7')}</MenuItem>"],
    ["<MenuItem value=\"last-30\">Last 30 Days</MenuItem>", "<MenuItem value=\"last-30\">{t('dashboard.presetLast30')}</MenuItem>"],
    ["<MenuItem value=\"this-month\">This Month</MenuItem>", "<MenuItem value=\"this-month\">{t('dashboard.presetThisMonth')}</MenuItem>"],
    ["<MenuItem value=\"prev-month\">Previous Month</MenuItem>", "<MenuItem value=\"prev-month\">{t('dashboard.presetPrevMonth')}</MenuItem>"],
    ["<MenuItem value=\"custom\">Custom Date Range</MenuItem>", "<MenuItem value=\"custom\">{t('dashboard.presetCustom')}</MenuItem>"],
    ["label=\"From\"", "label={t('dashboard.from')}"],
    ["label=\"To\"", "label={t('dashboard.to')}"],
    ["type=\"submit\" variant=\"contained\" color=\"secondary\" size=\"large\">\n                  Search\n                </Button>", "type=\"submit\" variant=\"contained\" color=\"secondary\" size=\"large\">\n                  {t('dashboard.search')}\n                </Button>"],
    // Card titles & labels
    ["Period Emissions", "{t('dashboard.periodEmissions')}"],
    ["% vs previous", "% \" + t('dashboard.vsPrevious')"],
    ["Daily Average", "{t('dashboard.dailyAverage')}"],
    ["Total {dateRangeSummary?.activityCount ?? 0} logs tracked", "{t('dashboard.totalLogsTracked')}: {dateRangeSummary?.activityCount ?? 0}"],
    ["Peak/Min Days", "{t('dashboard.peakMinDays')}"],
    ["Max: ", "{t('dashboard.max')}: "],
    ["Min: ", "{t('dashboard.min')}: "],
    ["Period Eco Score", "{t('dashboard.periodEcoScore')}"],
    ["Percentile standing: ", "{t('dashboard.percentileStanding')}: "],
    ["Goal Completion %", "{t('dashboard.goalCompletion')}"],
    ["On track for 2026 targets", "{t('dashboard.activeTargets')}"],
    ["Monthly Carbon Savings", "{t('dashboard.monthlyCarbonSavings')}"],
    ["CO₂e reduced vs baseline", "{t('dashboard.carbonReductions')}"],
    ["Highest Category / Most Improved", "{t('dashboard.highestCategory')}"],
    ["High: Transport (48%)", "{t('dashboard.max')}: Transport (48%)"],
    ["Improved: Food (-12%)", "{t('dashboard.mostImpact')}: Food (-12%)"],
    ["Estimated Annual Footprint", "{t('dashboard.estimatedAnnualFootprint')}"],
    ["CO₂e annual projection", "{t('dashboard.basedOnLogs')}"],
    // Tabs
    ["label=\"Emissions Trends\"", "label={t('dashboard.tabEmissionsOverTime')}"],
    ["label=\"Category Breakdown\"", "label={t('dashboard.tabCategoryBreakdown')}"],
    ["label=\"Personalized Recommendations\"", "label={t('dashboard.tabRecommendations')}"],
    ["label=\"Benchmarking & Insights\"", "label={t('dashboard.tabBenchmarking')}"],
    ["label=\"Recent Activity History\"", "label={t('dashboard.tabRecentLogs')}"],
    // Charts
    ["Daily Emissions Trend (Selected Period)", "{t('dashboard.chartDailyEmissions')}"],
    ["No activities logged in this range.", "{t('dashboard.noActivities')}"],
    ["Weekly Emissions Trend (All Time)", "{t('dashboard.chartWeeklyEmissions')}"],
    ["No summaries generated.", "{t('dashboard.noActivities')}"],
    ["Monthly Carbon Footprint Trend (All Time)", "{t('dashboard.chartMonthlyEmissions')}"],
    ["No monthly summaries generated.", "{t('dashboard.noActivities')}"],
    ["Donut Emission Breakdown (Selected Period)", "{t('dashboard.chartEmissionsDist')}"],
    ["Carbon Emissions Distribution", "{t('dashboard.chartEmissionsDist')}"],
    ["Emissions generated by your category choice", "{t('dashboard.emissionsByCategory')}"],
    ["How you compare to similar profiles", "{t('dashboard.howYouCompare')}"],
    ["Your Footprint", "{t('dashboard.yourFootprint')}"],
    ["Peer Average", "{t('dashboard.peerAverage')}"],
    ["National Target", "{t('dashboard.nationalTarget')}"],
    ["Benchmark Comparison (kg CO₂)", "{t('dashboard.chartBenchmarkComparison')}"],
    ["Sustainability Standing", "{t('dashboard.sustainabilityStanding')}"],
    ["You are doing great! Your carbon footprint is below the peer average.", "{t('dashboard.standingSummary')}"],
    // Recs tab
    ["Personalized Reduction recommendations", "{t('dashboard.personalizedRecs')}"],
    ["Tailored strategies based on your activity pattern to help you cut carbon.", "{t('dashboard.tailoredRecsSubtitle')}"],
    ["Estimated Savings", "{t('dashboard.estimatedSavings')}"],
    ["Status", "{t('dashboard.status')}"],
    ["Action", "{t('dashboard.action')}"],
    [">Implement<", ">{t('dashboard.implement')}<"],
    [">COMPLETED<", ">{t('dashboard.completed')}<"],
    [">ACTIVE<", ">{t('dashboard.active')}<"],
    ["No recommendations found. Keep logging to get AI tips!", "{t('dashboard.noRecs')}"],
    // Recent logs
    ["Latest tracked carbon actions.", "{t('dashboard.latestTrackedActions')}"],
    [">Category<", ">{t('dashboard.activityCategory')}<"],
    [">Activity Type<", ">{t('dashboard.activityType')}<"],
    [">Quantity<", ">{t('dashboard.activityQuantity')}<"],
    [">Emissions (kg)<", ">{t('dashboard.activityEmissions')}<"],
    [">Date<", ">{t('dashboard.activityDate')}<"],
    ["No activities logged for this period.", "{t('dashboard.noActivities')}"]
  ],
  "ActivityLogging.js": [
    ["import api from '../api';", "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';"],
    ["const ActivityLogging = () => {", "const ActivityLogging = () => {\n  const { t } = useTranslation();"],
    ["setError('Could not retrieve activity logs.');", "setError(t('activity.retrieveError'));"],
    ["setSuccess('Activity log updated successfully!');", "setSuccess(t('activity.updateSuccess'));"],
    ["setSuccess('Activity logged successfully!');", "setSuccess(t('activity.logSuccess'));"],
    ["setSuccess('Activity log deleted successfully!');", "setSuccess(t('activity.deleteSuccess'));"],
    ["setError('Quantity cannot be negative');", "setError(t('activity.negativeError'));"],
    ["setError(err.response?.data?.message || 'Logging action failed.');", "setError(err.response?.data?.message || t('activity.failedError'));"],
    ["setError('Deletion failed.');", "setError(t('activity.deleteError'));"],
    ["Log Carbon Activity", "{t('activity.logTitle')}"],
    ["Track your daily transport, utility, and diet choices to compute your real-time carbon footprint.", "{t('activity.logSubtitle')}"],
    ["label=\"Category\"", "label={t('activity.category')}"],
    ["label=\"Activity Type\"", "label={t('activity.type')}"],
    ["label={`Quantity (${CATEGORIES[category].unit})`}", "label={`${t('activity.quantity')} (${CATEGORIES[category].unit})`}"],
    ["label=\"Date\"", "label={t('activity.date')}"],
    ["Cancel Edit", "{t('activity.cancelEdit')}"],
    [">Update Log<", ">{t('activity.updateLog')}<"],
    [">Log Activity<", ">{t('activity.logBtn')}<"],
    ["label=\"Filter by Date\"", "label={t('activity.filterByDate')}"],
    ["Reset Filter", "{t('activity.resetFilter')}"],
    ["Daily Summary", "{t('activity.dailySummary')}"],
    ["Total emissions for filtered date: {dailyTotalEmission.toFixed(1)} kg CO₂", "{t('activity.totalEmissions')} {dailyTotalEmission.toFixed(1)} kg CO₂"],
    ["Recent Activity Logs (All-Time)", "{t('activity.recentLogsTitle')}"],
    [">Actions<", ">{t('activity.actions')}<"],
    ["No activities logged yet.", "{t('activity.noLogs')}"],
    ["window.confirm(\"Are you sure you want to delete this activity log?\")", "window.confirm(t('activity.deleteConfirm'))"]
  ],
  "Goals.js": [
    ["import api from '../api';", "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';"],
    ["const Goals = () => {", "const Goals = () => {\n  const { t } = useTranslation();"],
    ["setError('Could not retrieve goals.');", "setError(t('goals.retrieveError'));"],
    ["setError('Target reduction percentage must be between 1% and 100%');", "setError(t('goals.validationTarget'));"],
    ["setSuccess('Goal established successfully!');", "setSuccess(t('goals.successCreate'));"],
    ["setError(err.response?.data?.message || 'Failed to establish goal.');", "setError(err.response?.data?.message || t('goals.failCreate'));"],
    ["setSuccess('Goal deleted successfully!');", "setSuccess(t('goals.successDelete'));"],
    ["setError('Goal deletion failed.');", "setError(t('goals.failDelete'));"],
    ["Sustainability Goals", "{t('goals.title')}"],
    ["🎯 Establish Custom Sustainability Goal", "🎯 {t('goals.establishTitle')}"],
    ["label=\"Goal Title (e.g. 15% Commute Reduction)\"", "label={t('goals.formTitle')}"],
    ["label=\"Target Reduction (%)\"", "label={t('goals.formTarget')}"],
    ["label=\"Start Date\"", "label={t('goals.formStart')}"],
    ["label=\"Target End Date\"", "label={t('goals.formEnd')}"],
    ["{loading ? 'Creating...' : 'Create Goal'}", "{loading ? t('goals.formCreating') : t('goals.formSubmit')}"],
    ["Your Goals & Target Progress", "{t('goals.listTitle')}"],
    ["You don't have any active carbon reduction goals.", "{t('goals.noGoals')}"],
    ["Target: {goal.targetReductionPercentage}% Reduction", "{t('goals.targetReduction')} {goal.targetReductionPercentage}% Reduction"],
    [" {goal.startDate} to {goal.targetDate} ", " {goal.startDate} + t('goals.to') + {goal.targetDate} "]
  ],
  "Recommendations.js": [
    ["import api from '../api';", "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';"],
    ["const Recommendations = () => {", "const Recommendations = () => {\n  const { t } = useTranslation();"],
    ["setError('Could not retrieve personalized recommendations.');", "setError(t('recs.retrieveError'));"],
    ["setSuccess(`Recommendation marked as ${newStatus.replace('_', ' ').toLowerCase()}!`);", "setSuccess(t('recs.successUpdate'));"],
    ["setError('Failed to update recommendation status.');", "setError(t('recs.failUpdate'));"],
    ["Personalized Eco Recommendations", "{t('recs.insufficientDataTitle')}"],
    ["We need a little more activity data to generate personalized recommendations. Log at least 3 activities to enable our smart engine.", "{t('recs.insufficientDataDesc')}"],
    ["Go To Activity Logs", "{t('recs.goToLogs')}"],
    ["AI-powered recommendations based on your activity pattern to help you cut carbon emissions.", "{t('recs.subtitle')}"],
    ["label=\"Active Recommendations\"", "label={t('recs.tabActive')}"],
    ["label=\"Recommendation History\"", "label={t('recs.tabHistory')}"],
    ["label=\"Recommendation Analytics\"", "label={t('recs.tabAnalytics')}"],
    ["label=\"Filter by Category\"", "label={t('recs.filterCategory')}"],
    ["<MenuItem value=\"ALL\">All Categories</MenuItem>", "<MenuItem value=\"ALL\">{t('recs.filterAll')}</MenuItem>"],
    ["<MenuItem value=\"TRANSPORT\">Transport</MenuItem>", "<MenuItem value=\"TRANSPORT\">{t('dashboard.catTransport')}</MenuItem>"],
    ["<MenuItem value=\"ELECTRICITY\">Electricity</MenuItem>", "<MenuItem value=\"ELECTRICITY\">{t('dashboard.catElectricity')}</MenuItem>"],
    ["<MenuItem value=\"FOOD\">Food</MenuItem>", "<MenuItem value=\"FOOD\">{t('dashboard.catFood')}</MenuItem>"],
    ["<MenuItem value=\"SHOPPING\">Shopping</MenuItem>", "<MenuItem value=\"SHOPPING\">{t('dashboard.catShopping')}</MenuItem>"],
    ["label=\"Analysis Period\"", "label={t('recs.periodLabel')}"],
    ["<MenuItem value=\"7DAYS\">Last 7 Days</MenuItem>", "<MenuItem value=\"7DAYS\">{t('recs.period7')}</MenuItem>"],
    ["<MenuItem value=\"30DAYS\">Last 30 Days</MenuItem>", "<MenuItem value=\"30DAYS\">{t('recs.period30')}</MenuItem>"],
    ["<MenuItem value=\"CUSTOM\">Custom Range</MenuItem>", "<MenuItem value=\"CUSTOM\">{t('recs.periodCustom')}</MenuItem>"],
    ["label=\"From\"", "label={t('recs.from')}"],
    ["label=\"To\"", "label={t('recs.to')}"],
    ["type=\"submit\" variant=\"contained\" color=\"secondary\">\n                  Apply Filter\n                </Button>", "type=\"submit\" variant=\"contained\" color=\"secondary\">\n                  {t('recs.search')}\n                </Button>"],
    ["Estimated Period Savings: ", "{t('recs.estSavings')}"],
    ["Active Recommendations: ", "{t('recs.activeRecsCount')}"],
    ["Completed Tasks: ", "{t('recs.completedRecsCount')}"],
    ["No active recommendations matching your filter.", "{t('recs.noActive')}"],
    ["CRITICAL", "{t('recs.badgeCritical')}"],
    ["HIGH", "{t('recs.badgeHigh')}"],
    ["MEDIUM", "{t('recs.badgeMedium')}"],
    ["LOW", "{t('recs.badgeLow')}"],
    ["Potential Savings: ", "{t('recs.potentialSavings')}"],
    [" kg CO2", "{t('recs.kg')}"],
    ["Implement Action", "{t('recs.actionImplement')}"],
    ["Ignore Recommendation", "{t('recs.actionIgnore')}"],
    ["Snooze (24h)", "{t('recs.actionSnooze')}"],
    ["View Details", "{t('recs.actionDetails')}"],
    ["No historical recommendations found.", "{t('recs.noHistory')}"],
    ["Re-activate", "{t('recs.actionReactivate')}"],
    ["Total Emissions Averted", "{t('recs.totalAverted')}"],
    ["Recommendation Implementation Rate", "{t('recs.implementationRate')}"],
    ["Estimated Carbon Savings by Category", "{t('recs.categorySavingsTitle')}"],
    ["Recommendation Status Distribution", "{t('recs.statusDistribution')}"],
    ["Not enough recommendation data to display charts.", "{t('recs.noDataAnalytics')}"],
    ["Recommendation Analysis Details", "{t('recs.dialogTitle')}"],
    ["Close", "{t('recs.dialogClose')}"],
    ["Potential Carbon Reduction: ", "{t('recs.dialogPotential')}"],
    ["Difficulty / Feasibility Level: ", "{t('recs.dialogDifficulty')}"],
    ["Estimated Implementation Cost: ", "{t('recs.dialogCost')}"],
    ["Target Mitigation Timeline: ", "{t('recs.dialogTimeline')}"],
    ["Why this recommendation is generated:", "{t('recs.dialogWhy')}"],
    ["Actionable Implementation Steps:", "{t('recs.dialogHow')}"]
  ],
  "Leaderboard.js": [
    ["import api from '../api';", "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';"],
    ["const Leaderboard = () => {", "const Leaderboard = () => {\n  const { t } = useTranslation();"],
    ["setError('Could not retrieve leaderboard standings.');", "setError(t('leaderboard.retrieveError'));"],
    ["Community Leaderboard", "{t('leaderboard.title')}"],
    ["🏆 Monthly Emissions Ranking", "🏆 {t('leaderboard.subtitle')}"],
    ["No standings available.", "{t('leaderboard.noUsers')}"],
    ["Active Participant", "{t('leaderboard.activeParticipant')}"],
    ["kg CO2 logged", "{t('leaderboard.savings')}"],
    ["🏅 Your Earned Achievements", "🏅 {t('profile.tabAchievements')}"],
    ["No Badges Earned Yet", "{t('profile.badgesLocked')}"],
    ["Log daily activities and complete your target reduction goals to unlock community accomplishments!", "{t('profile.badgesLockedDesc')}"],
    ["Awarded: ", "{t('profile.badgesEarnedOn')}"]
  ],
  "Feedback.js": [
    ["import api from '../api';", "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';"],
    ["const Feedback = () => {", "const Feedback = () => {\n  const { t } = useTranslation();"],
    ["setSuccess('Feedback submitted successfully! Thank you for helping us improve.');", "setSuccess(t('feedback.successMsg'));"],
    ["setError('Failed to submit feedback.');", "setError(t('feedback.errorMsg'));"],
    ["Submit Platform Feedback", "{t('feedback.title')}"],
    ["Help us improve Carbon Tracker. Share your experience, report bugs, or request features.", "{t('feedback.subtitle')}"],
    ["label=\"Feedback Category\"", "label={t('feedback.formCategory')}"],
    ["label=\"Star Rating (1-5)\"", "label={t('feedback.formRating')}"],
    ["label=\"Written Feedback\"", "label={t('feedback.formText')}"],
    ["{loading ? 'Submitting...' : 'Submit Feedback'}", "{loading ? t('feedback.submitting') : t('feedback.formSubmit')}"]
  ],
  "LoginPage.js": [
    ["import { useAuth } from '../context/AuthContext';", "import { useAuth } from '../context/AuthContext';\nimport { useTranslation } from '../context/LanguageContext';"],
    ["const LoginPage = () => {", "const LoginPage = () => {\n  const { t } = useTranslation();"],
    ["Measure, Reduce, and <Box component=\"span\" sx={{ color: 'primary.main' }}>Offset</Box> Your Footprint.", "{t('auth.loginHeroTitle')}"],
    ["Join thousands of community members logging their daily activities, competing on the leaderboard, and completing carbon reduction goals.", "{t('auth.loginHeroDesc')}"],
    ["TONS CO2 SAVED", "{t('auth.tonsSaved')}"],
    ["ACTIVITIES LOGGED", "{t('auth.activitiesLogged')}"],
    ["Sign in to manage your carbon footprint logs and tracker.", "{t('auth.loginSubtitle')}"],
    ["label=\"Email Address\"", "label={t('auth.email')}"],
    ["label=\"Password\"", "label={t('auth.password')}"],
    ["Forgot Password?", "{t('auth.forgot_password')}"],
    ["{loading ? 'Signing in...' : 'Sign In'}", "{loading ? t('auth.loggingIn') : t('auth.login')}"],
    ["<Divider>Or</Divider>", "<Divider>{t('auth.or')}</Divider>"],
    ["Sign In with Google", "{t('auth.googleLogin')}"],
    ["Don't have an account?", "{t('auth.noAccount')}"],
    ["Register here", "{t('auth.registerHere')}"]
  ],
  "RegisterPage.js": [
    ["import { useAuth } from '../context/AuthContext';", "import { useAuth } from '../context/AuthContext';\nimport { useTranslation } from '../context/LanguageContext';"],
    ["const RegisterPage = () => {", "const RegisterPage = () => {\n  const { t } = useTranslation();"],
    ["Start Your <Box component=\"span\" sx={{ color: 'primary.main' }}>Green</Box> Journey Today.", "{t('auth.registerHeroTitle')}"],
    ["Create your account to unlock personalized recommendations, track your sustainability logs, and visualize progress in real-time.", "{t('auth.registerHeroDesc')}"],
    ["Did you know?", "{t('auth.didYouKnow')}"],
    ["Logging activities daily helps build eco-conscious habits. Average users reduce their carbon output by 15% in their first month!", "{t('auth.didYouKnowDesc')}"],
    ["Join the carbon tracking platform and begin measuring impact.", "{t('auth.registerSubtitle')}"],
    ["label=\"Full Name\"", "label={t('auth.fullName')}"],
    ["label=\"Email Address\"", "label={t('auth.email')}"],
    ["label=\"Mobile Number\"", "label={t('auth.mobileNumber')}"],
    ["label=\"Password\"", "label={t('auth.password')}"],
    ["label=\"Confirm Password\"", "label={t('auth.confirmPassword')}"],
    ["{loading ? 'Registering...' : 'Register'}", "{loading ? t('auth.registering') : t('auth.register')}"],
    ["Already have an account?", "{t('auth.hasAccount')}"],
    ["Sign in here", "{t('auth.loginHere')}"],
    ["return \"Password must be at least 8 characters long.\";", "return t('auth.validationPasswordLength');"],
    ["return \"Password must be alphanumeric (contain both letters and numbers).\";", "return t('auth.validationPasswordAlphanumeric');"],
    ["return \"Password must contain at least one special character (e.g. @, #, $, %, etc.).\";", "return t('auth.validationPasswordSpecial');"],
    ["setError(\"Passwords do not match\");", "setError(t('profile.passwordMatchError'));"],
    ["setSuccess(\"Registration completed! Redirecting to login...\");", "setSuccess(t('auth.registrationSuccess'));"]
  ],
  "ForgotPasswordPage.js": [
    ["import api from '../api';", "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';"],
    ["const ForgotPasswordPage = () => {", "const ForgotPasswordPage = () => {\n  const { t } = useTranslation();"],
    ["Forgot Password", "{t('auth.forgotPasswordTitle')}"],
    ["Enter your registered email address to receive a 6-digit verification code.", "{t('auth.forgotPasswordSubtitle')}"],
    ["label=\"Email Address\"", "label={t('auth.email')}"],
    ["{loading ? 'Sending OTP...' : 'Send OTP'}", "{loading ? t('auth.forgotPasswordSending') : t('auth.forgotPasswordBtn')}"],
    ["Back to Sign In", "{t('auth.loginHere')}"]
  ],
  "OtpVerificationPage.js": [
    ["import api from '../api';", "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';"],
    ["const OtpVerificationPage = () => {", "const OtpVerificationPage = () => {\n  const { t } = useTranslation();"],
    ["Verify OTP", "{t('auth.otpTitle')}"],
    ["Enter the 6-digit code sent to <strong>{email}</strong>.", "<Box component=\"span\">{t('auth.otpSubtitle')} <strong>{email}</strong></Box>"],
    ["label=\"Email Address\"", "label={t('auth.email')}"],
    ["label=\"6-Digit OTP\"", "label={t('auth.otpLabel')}"],
    ["{loading ? 'Verifying...' : 'Verify Code'}", "{loading ? t('auth.otpsending') : t('auth.otpBtnVerify')}"],
    ["Resend OTP", "{t('auth.resendOtp')}"],
    ["Back to Sign In", "{t('auth.loginHere')}"]
  ],
  "ResetPasswordPage.js": [
    ["import api from '../api';", "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';"],
    ["const ResetPasswordPage = () => {", "const ResetPasswordPage = () => {\n  const { t } = useTranslation();"],
    ["Reset Password", "{t('auth.resetPasswordTitle')}"],
    ["Set your new account password.", "{t('auth.resetPasswordSubtitle')}"],
    ["label=\"New Password\"", "label={t('profile.settingsNewPassword')}"],
    ["label=\"Confirm Password\"", "label={t('auth.confirmPassword')}"],
    ["{loading ? 'Updating Password...' : 'Reset Password'}", "{loading ? t('auth.resetPasswordSending') : t('auth.resetPasswordBtn')}"],
    ["Back to Sign In", "{t('auth.loginHere')}"],
    ["setError('Passwords do not match');", "setError(t('profile.passwordMatchError'));"]
  ]
};

// Process each file
for (const [filename, fileRepls] of Object.entries(fileReplacements)) {
  const filepath = path.join(pagesDir, filename);
  if (!fs.existsSync(filepath)) {
    console.error(`File not found: ${filename}`);
    continue;
  }
  let content = fs.readFileSync(filepath, 'utf8');
  let modified = false;

  for (const [target, replacement] of fileRepls) {
    if (content.includes(target)) {
      content = content.split(target).join(replacement);
      modified = true;
    } else {
      console.warn(`[Warning] target string not found in ${filename}: "${target.slice(0, 40)}"`);
    }
  }

  if (modified) {
    fs.writeFileSync(filepath, content, 'utf8');
    console.log(`Successfully translated: ${filename}`);
  } else {
    console.log(`No changes made to: ${filename}`);
  }
}

console.log("Safe page updates batch 1 completed!");
