const fs = require('fs');
const path = require('path');

const pagesDir = path.join(__dirname, 'frontend', 'src', 'pages');

const replacements = {
  "AnalyticsPage.js": [
    { target: "const AnalyticsPage = () => {", replacement: "const AnalyticsPage = () => {\n  const { t } = useTranslation();" },
    { target: "import api from '../api';", replacement: "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';" },
    { target: "Advanced Analytics & Intelligence", replacement: "{t('admin.reportsTitle')}" },
    { target: "Deep-dive category breakdown ({selectedCategory}), period comparison, predictive forecasts, and carbon potential engine.", replacement: "{t('dashboard.analyticsSubtitle')}" },
    { target: "Download CSV", replacement: "{t('dashboard.exportCSV')}" },
    { target: "Download PDF", replacement: "{t('dashboard.exportPDF')}" },
    { target: "label=\"Period Type\"", replacement: "label={t('recs.periodLabel')}" },
    { target: "<MenuItem value=\"DAILY\">Daily</MenuItem>", replacement: "<MenuItem value=\"DAILY\">{t('dashboard.presetToday')}</MenuItem>" },
    { target: "<MenuItem value=\"WEEKLY\">Weekly</MenuItem>", replacement: "<MenuItem value=\"WEEKLY\">{t('dashboard.presetLast7')}</MenuItem>" },
    { target: "<MenuItem value=\"MONTHLY\">Monthly</MenuItem>", replacement: "<MenuItem value=\"MONTHLY\">{t('dashboard.presetThisMonth')}</MenuItem>" },
    { target: "<MenuItem value=\"YEARLY\">Yearly</MenuItem>", replacement: "<MenuItem value=\"YEARLY\">{t('dashboard.presetCustom')}</MenuItem>" },
    { target: "label=\"Select Date\"", replacement: "label={t('activity.date')}" },
    { target: "label=\"Select Week\"", replacement: "label={t('recs.periodLabel')}" },
    { target: "label=\"Select Month\"", replacement: "label={t('profile.historyTitle')}" },
    { target: "label=\"Select Year\"", replacement: "label={t('dashboard.presetCustom')}" },
    { target: "label=\"From\"", replacement: "label={t('dashboard.from')}" },
    { target: "label=\"To\"", replacement: "label={t('dashboard.to')}" },
    { target: "label=\"Category Selection\"", replacement: "label={t('activity.category')}" },
    { target: "<MenuItem value=\"ALL\">All Categories</MenuItem>", replacement: "<MenuItem value=\"ALL\">{t('recs.filterAll')}</MenuItem>" },
    { target: "<MenuItem value=\"TRANSPORT\">Transport</MenuItem>", replacement: "<MenuItem value=\"TRANSPORT\">{t('dashboard.catTransport')}</MenuItem>" },
    { target: "<MenuItem value=\"ELECTRICITY\">Electricity</MenuItem>", replacement: "<MenuItem value=\"ELECTRICITY\">{t('dashboard.catElectricity')}</MenuItem>" },
    { target: "<MenuItem value=\"FOOD\">Food</MenuItem>", replacement: "<MenuItem value=\"FOOD\">{t('dashboard.catFood')}</MenuItem>" },
    { target: "<MenuItem value=\"SHOPPING\">Shopping</MenuItem>", replacement: "<MenuItem value=\"SHOPPING\">{t('dashboard.catShopping')}</MenuItem>" },
    { target: "label=\"Analytics Dashboard\"", replacement: "label={t('nav.dashboard')}" },
    { target: "label=\"Historical Logs\"", replacement: "label={t('profile.tabHistory')}" },
    { target: "label=\"Milestones Timeline\"", replacement: "label={t('profile.tabAchievements')}" },
    { target: "label=\"Sustainability standing\"", replacement: "label={t('dashboard.sustainabilityStanding')}" },
    { target: "Total Period Carbon Footprint", replacement: "{t('dashboard.periodEmissions')}" },
    { target: "Daily Average", replacement: "{t('dashboard.dailyAverage')}" },
    { target: "Estimated Annual Footprint", replacement: "{t('dashboard.estimatedAnnualFootprint')}" },
    { target: "Peak Day", replacement: "{t('dashboard.max')}" },
    { target: "Lowest Day", replacement: "{t('dashboard.min')}" },
    { target: "Period-Over-Period Comparison", replacement: "{t('dashboard.tabEmissionsOverTime')}" },
    { target: "Predictive Emission Forecast (Next 3 Periods)", replacement: "{t('dashboard.chartDailyEmissions')}" },
    { target: "Emissions (kg CO₂)", replacement: "{t('dashboard.emissions')}" },
    { target: "Historical Cumulative Carbon Logged (kg CO₂)", replacement: "{t('activity.recentLogsTitle')}" },
    { target: "Eco Score Progress Indicator", replacement: "{t('dashboard.periodEcoScore')}" },
    { target: "Ecological Journey Milestones", replacement: "{t('profile.tabAchievements')}" }
  ],
  "LandingPage.js": [
    { target: "const LandingPage = () => {", replacement: "const LandingPage = () => {\n  const { t } = useTranslation();" },
    { target: "import { ColorModeContext } from '../App';", replacement: "import { ColorModeContext } from '../App';\nimport { useTranslation } from '../context/LanguageContext';" },
    { target: "Empowering Net-Zero Transitions", replacement: "{t('landing.heroTitle')}" },
    { target: "The comprehensive platform to track carbon footprints, achieve green goals, earn rewards, and optimize your company’s ecological performance.", replacement: "{t('landing.heroSubtitle')}" },
    { target: "Get Started Free", replacement: "{t('landing.getStarted')}" },
    { target: "View Demo Console", replacement: "{t('landing.viewDemo')}" },
    { target: "Enterprise Ecological Intelligence", replacement: "{t('landing.featuresTitle')}" },
    { target: "Automated Activity Logging", replacement: "{t('landing.feature1Title')}" },
    { target: "Log transport, electricity, food, and shopping habits effortlessly with intelligent real-time carbon conversion factors.", replacement: "{t('landing.feature1Desc')}" },
    { target: "Category Intelligence & Forecasts", replacement: "{t('landing.feature2Title')}" },
    { target: "Deep dive into 4 core emission categories with predictive trend lines, peak day analysis, and YoY period comparisons.", replacement: "{t('landing.feature2Desc')}" },
    { target: "Personalized Recommendations", replacement: "{t('dashboard.tabRecommendations')}" },
    { target: "Get actionable eco-tips calculated with estimated monthly and annual carbon savings tailored to your consumption habits.", replacement: "{t('dashboard.tailoredRecsSubtitle')}" },
    { target: "Leaderboard & Achievements", replacement: "{t('profile.tabAchievements')}" },
    { target: "Earn gamified eco-badges (Eco Saver, 7-Day Streak) and climb the platform rankings as you reduce your footprint.", replacement: "{t('leaderboard.subtitle')}" },
    { target: "Enterprise Benchmarking", replacement: "{t('nav.benchmarking')}" },
    { target: "Compare your progress against platform averages and organization benchmarks with percentile ranking insights.", replacement: "{t('dashboard.howYouCompare')}" },
    { target: "Audit-Ready Export Center", replacement: "{t('nav.reports')}" },
    { target: "Generate comprehensive PDF and CSV sustainability compliance reports for personal audit or enterprise reporting.", replacement: "{t('dashboard.analyticsSubtitle')}" },
    { target: "What Sustainability Leaders Say", replacement: "{t('landing.testimonialsTitle')}" },
    { target: "Ready to Start Your Sustainability Journey?", replacement: "{t('landing.ctaTitle')}" },
    { target: "Join thousands of users and organizations tracking and reducing their carbon output.", replacement: "{t('landing.ctaDesc')}" },
    { target: "Register Account", replacement: "{t('landing.ctaBtn')}" },
    { target: "label: 'Total Emissions Tracked', value: '1,245,800 kg', subtext: 'CO₂ equivalent'", replacement: "label: t('landing.statsTotalEmissions'), value: '1,245,800 kg', subtext: t('landing.co2Equiv')" },
    { target: "label: 'Active Eco Warriors', value: '28,400+', subtext: 'Global users'", replacement: "label: t('landing.statsActiveWarriors'), value: '28,400+', subtext: t('landing.globalUsers')" },
    { target: "label: 'Sustainability Goals', value: '14,250', subtext: 'Achieved this year'", replacement: "label: t('landing.statsGoals'), value: '14,250', subtext: t('landing.achievedThisYear')" },
    { target: "label: 'Net Carbon Saved', value: '382,500 kg', subtext: 'Verified reduction'", replacement: "label: t('landing.statsCarbonSaved'), value: '382,500 kg', subtext: t('landing.verifiedReduction')" }
  ],
  "OrganizationDashboard.js": [
    { target: "const OrganizationDashboard = () => {", replacement: "const OrganizationDashboard = () => {\n  const { t } = useTranslation();" },
    { target: "import { useAuth } from '../context/AuthContext';", replacement: "import { useAuth } from '../context/AuthContext';\nimport { useTranslation } from '../context/LanguageContext';" },
    { target: "Organization Sustainability", replacement: "{t('org.title')}" },
    { target: "Benchmark and track departmental carbon metrics, invite teammates, and manage carbon budgets.", replacement: "{t('org.subtitle')}" },
    { target: "You are not member of any organization. Create a new one or join using an invite code.", replacement: "{t('org.noOrg')}" },
    { target: "Create a New Organization", replacement: "{t('org.createTitle')}" },
    { target: "Join an Existing Organization", replacement: "{t('org.joinTitle')}" },
    { target: "label=\"Organization Name\"", replacement: "label={t('org.orgName')}" },
    { target: "label=\"Invite Code (6 characters)\"", replacement: "label={t('org.inviteCode')}" },
    { target: "Join Organization", replacement: "{t('org.joinBtn')}" },
    { target: "Create Organization", replacement: "{t('org.createBtn')}" },
    { target: "Invite Code", replacement: "{t('org.inviteCodeLabel')}" },
    { target: "Organization Name", replacement: "{t('org.orgName')}" },
    { target: "Invite Code (6 characters)", replacement: "{t('org.inviteCode')}" },
    { target: "Organization Name", replacement: "{t('org.orgName')}" },
    { target: "Invite Code (6 characters)", replacement: "{t('org.inviteCode')}" },
    { target: "Team Members", replacement: "{t('org.members')}" },
    { target: "Share this code to invite teammates: ", replacement: "t('org.inviteCodeShare')" },
    { target: "Teammates Contribution Leaderboard", replacement: "{t('org.ranking')}" },
    { target: "Name", replacement: "{t('org.name')}" },
    { target: "Role", replacement: "{t('org.role')}" },
    { target: "Monthly Footprint (kg)", replacement: "{t('org.monthlyFootprint')}" },
    { target: "Points", replacement: "{t('org.points')}" },
    { target: "Organization established successfully!", replacement: "t('org.successCreate')" },
    { target: "Joined organization successfully!", replacement: "t('org.successJoin')" },
    { target: "Failed to execute organization operation.", replacement: "t('org.failAction')" }
  ],
  "AdminDashboard.js": [
    { target: "const AdminDashboard = () => {", replacement: "const AdminDashboard = () => {\n  const { t } = useTranslation();" },
    { target: "import api from '../api';", replacement: "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';" },
    { target: "Admin Control Console", replacement: "{t('admin.dashboardTitle')}" },
    { target: "Monitor system users, configure carbon factors, view platform analytics, and manage support tickets.", replacement: "{t('admin.dashboardSubtitle')}" },
    { target: "Total Platform Users", replacement: "{t('admin.statsUsers')}" },
    { target: "Total Platform Emissions (kg)", replacement: "{t('admin.statsEmissions')}" },
    { target: "Active Organizations", replacement: "{t('admin.statsOrgs')}" },
    { target: "Pending Support Tickets", replacement: "{t('admin.statsTickets')}" },
    { target: "Admin Quick Actions", replacement: "{t('admin.quickActions')}" },
    { target: "User Account Logs", replacement: "{t('admin.actionUsers')}" },
    { target: "Emission Factor Configurator", replacement: "{t('admin.actionFactors')}" },
    { target: "Support Tickets Queue", replacement: "{t('admin.actionTickets')}" },
    { target: "Platform Performance Reports", replacement: "{t('admin.actionReports')}" }
  ],
  "UserManagement.js": [
    { target: "const UserManagement = () => {", replacement: "const UserManagement = () => {\n  const { t } = useTranslation();" },
    { target: "import api from '../api';", replacement: "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';" },
    { target: "User Analytics & Accounts", replacement: "{t('admin.usersTitle')}" },
    { target: "Inspect registered user details, activity histories, and assign roles.", replacement: "{t('admin.usersSubtitle')}" },
    { target: "User ID", replacement: "{t('admin.usersTableId')}" },
    { target: "Full Name", replacement: "{t('admin.usersTableName')}" },
    { target: "Email Address", replacement: "{t('admin.usersTableEmail')}" },
    { target: "Role", replacement: "{t('admin.usersTableRole')}" },
    { target: "Actions", replacement: "{t('admin.usersTableActions')}" },
    { target: "Change Role", replacement: "{t('admin.usersChangeRole')}" }
  ],
  "EmissionFactorManagement.js": [
    { target: "const EmissionFactorManagement = () => {", replacement: "const EmissionFactorManagement = () => {\n  const { t } = useTranslation();" },
    { target: "import api from '../api';", replacement: "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';" },
    { target: "Carbon Emission Coefficient Configuration", replacement: "{t('admin.factorsTitle')}" },
    { target: "Configure carbon multiplier coefficients (kg CO₂ per unit) used in platform calculations.", replacement: "{t('admin.factorsSubtitle')}" },
    { target: "Configure New Emission Factor", replacement: "{t('admin.factorsAddTitle')}" },
    { target: "Edit Carbon Coefficient", replacement: "{t('admin.factorsEditTitle')}" },
    { target: "label=\"Activity Category\"", replacement: "label={t('admin.factorCategory')}" },
    { target: "label=\"Activity Type\"", replacement: "label={t('admin.factorType')}" },
    { target: "label=\"Coefficient (kg CO₂ / unit)\"", replacement: "label={t('admin.factorCoefficient')}" },
    { target: "label=\"Unit Measure\"", replacement: "label={t('admin.factorUnit')}" },
    { target: "Category", replacement: "{t('admin.factorsTableCategory')}" },
    { target: "Activity Type", replacement: "{t('admin.factorsTableType')}" },
    { target: "Coefficient", replacement: "{t('admin.factorsTableCoefficient')}" },
    { target: "Unit", replacement: "{t('admin.factorsTableUnit')}" },
    { target: "Actions", replacement: "{t('admin.factorsTableActions')}" },
    { target: "Emission factor created successfully!", replacement: "t('admin.factorsSuccessCreate')" },
    { target: "Emission factor updated successfully!", replacement: "t('admin.factorsSuccessUpdate')" },
    { target: "Emission factor deleted successfully!", replacement: "t('admin.factorsSuccessDelete')" }
  ],
  "FeedbackManagement.js": [
    { target: "const FeedbackManagement = () => {", replacement: "const FeedbackManagement = () => {\n  const { t } = useTranslation();" },
    { target: "import api from '../api';", replacement: "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';" },
    { target: "User Feedback Records", replacement: "{t('admin.feedbackTitle')}" },
    { target: "View star ratings and written reports submitted by platform users.", replacement: "{t('admin.feedbackSubtitle')}" },
    { target: "User", replacement: "{t('admin.feedbackTableUser')}" },
    { target: "Category", replacement: "{t('admin.feedbackTableCategory')}" },
    { target: "Rating", replacement: "{t('admin.feedbackTableRating')}" },
    { target: "Feedback Text", replacement: "{t('admin.feedbackTableText')}" },
    { target: "Submission Date", replacement: "{t('admin.feedbackTableDate')}" }
  ],
  "ReportsAnalytics.js": [
    { target: "const ReportsAnalytics = () => {", replacement: "const ReportsAnalytics = () => {\n  const { t } = useTranslation();" },
    { target: "import api from '../api';", replacement: "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';" },
    { target: "Platform Performance Reporting", replacement: "{t('admin.reportsTitle')}" },
    { target: "Inspect system-wide carbon savings, cumulative activities, and ecological scores.", replacement: "{t('admin.reportsSubtitle')}" },
    { target: "Platform Emissions Trend", replacement: "{t('admin.reportsEmissionsTrend')}" },
    { target: "Platform Mitigation Savings", replacement: "{t('admin.reportsSavingsTrend')}" },
    { target: "Cumulative Activity Log Count", replacement: "{t('admin.reportsActivitiesTrend')}" }
  ],
  "AdminSupportDashboard.js": [
    { target: "const AdminSupportDashboard = () => {", replacement: "const AdminSupportDashboard = () => {\n  const { t } = useTranslation();" },
    { target: "import api from '../api';", replacement: "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';" },
    { target: "Customer Support Tickets Queue", replacement: "{t('admin.supportTitle')}" },
    { target: "Triage and resolve technical support inquiries submitted by users.", replacement: "{t('admin.supportSubtitle')}" },
    { target: "Ticket ID", replacement: "{t('admin.supportTicketId')}" },
    { target: "User", replacement: "{t('admin.supportUser')}" },
    { target: "Subject", replacement: "{t('admin.supportSubject')}" },
    { target: "Category", replacement: "{t('admin.supportCategory')}" },
    { target: "Priority", replacement: "{t('admin.supportPriority')}" },
    { target: "Status", replacement: "{t('admin.supportStatus')}" },
    { target: "Opened", replacement: "{t('admin.supportDate')}" },
    { target: "Actions", replacement: "{t('admin.supportActions')}" },
    { target: "Resolve & Close", replacement: "{t('admin.supportResolve')}" },
    { target: "Open Ticket Conversation", replacement: "{t('admin.supportChat')}" }
  ],
  "Profile.js": [
    { target: "const Profile = () => {", replacement: "const Profile = () => {\n  const { t } = useTranslation();" },
    { target: "import api from '../api';", replacement: "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';" },
    { target: "User Profile Center", replacement: "{t('profile.title')}" },
    { target: "label=\"Profile Information\"", replacement: "label={t('profile.tabProfile')}" },
    { target: "label=\"Activity History\"", replacement: "label={t('profile.tabHistory')}" },
    { target: "label=\"Badges & Badging\"", replacement: "label={t('profile.tabBadges')}" },
    { target: "label=\"Carbon Certificates\"", replacement: "label={t('profile.tabCertificates')}" },
    { target: "label=\"Achievements\"", replacement: "label={t('profile.tabAchievements')}" },
    { target: "label=\"Rewards & Levels\"", replacement: "label={t('profile.tabRewards')}" },
    { target: "label=\"Notifications\"", replacement: "label={t('profile.tabNotifications')}" },
    { target: "label=\"Settings\"", replacement: "label={t('profile.tabSettings')}" },
    { target: "Edit Profile Details", replacement: "{t('profile.editTitle')}" },
    { target: "label=\"Full Name\"", replacement: "label={t('profile.fullName')}" },
    { target: "label=\"Email Address\"", replacement: "label={t('profile.email')}" },
    { target: "label=\"Mobile Number\"", replacement: "label={t('profile.mobileNumber')}" },
    { target: "label=\"Date of Birth\"", replacement: "label={t('profile.dob')}" },
    { target: "label=\"Gender\"", replacement: "label={t('profile.gender')}" },
    { target: "label=\"Sustainability Preferences\"", replacement: "label={t('profile.preferences')}" },
    { target: "placeholder=\"e.g. Vegetarian, EV Driver, Solar Energy user...\"", replacement: "placeholder={t('profile.preferencesPlaceholder')}" },
    { target: "label=\"Country\"", replacement: "label={t('profile.country')}" },
    { target: "label=\"State\"", replacement: "label={t('profile.state')}" },
    { target: "label=\"City\"", replacement: "label={t('profile.city')}" },
    { target: "Save Changes", replacement: "{t('profile.saveChanges')}" },
    { target: "Saving...", replacement: "{t('profile.saving')}" },
    { target: "Profile updated successfully!", replacement: "t('profile.successUpdate')" },
    { target: "Failed to update profile info.", replacement: "t('profile.errorUpdate')" },
    { target: "Tracked Carbon Log History", replacement: "{t('profile.historyTitle')}" },
    { target: "label=\"All Logs\"", replacement: "label={t('profile.historyFilterAll')}" },
    { target: "label=\"Today\"", replacement: "label={t('profile.historyFilterToday')}" },
    { target: "label=\"Last 7 Days\"", replacement: "label={t('profile.historyFilter7')}" },
    { target: "label=\"Last 30 Days\"", replacement: "label={t('profile.historyFilter30')}" },
    { target: "Page ", replacement: "t('profile.historyPage')" },
    { target: " of ", replacement: " + t('profile.historyOf') + " },
    { target: "Your Carbon Badges Portfolio", replacement: "{t('profile.badgesTitle')}" },
    { target: "label=\"Unlocked Badges\"", replacement: "label={t('profile.badgesUnlocked')}" },
    { target: "label=\"Locked Badges\"", replacement: "label={t('profile.badgesLocked')}" },
    { target: "label=\"All Badges\"", replacement: "label={t('profile.badgesAll')}" },
    { target: "Earned on: ", replacement: "t('profile.badgesEarnedOn')" },
    { target: "Locked - Complete objectives to earn this badge", replacement: "{t('profile.badgesLockedDesc')}" },
    { target: "Carbon Mitigations Digital Certificates", replacement: "{t('profile.certsTitle')}" },
    { target: "Tamper-proof credentials certifying your commitment to lowering carbon emissions.", replacement: "{t('profile.certsSubtitle')}" },
    { target: "Issued: ", replacement: "t('profile.certsIssued')" },
    { target: "Verified Secure Document", replacement: "{t('profile.certsVerified')}" },
    { target: "View Secure Doc", replacement: "{t('profile.certsViewDoc')}" },
    { target: "Share Certificate", replacement: "{t('profile.certsShare')}" },
    { target: "Share link copied to clipboard!", replacement: "t('profile.certsCopied')" },
    { target: "You have not earned any certificates yet. Achieve goals to generate verified certificates.", replacement: "{t('profile.certsNoCerts')}" },
    { target: "Secure Digital Green Certificate", replacement: "{t('profile.certsModalTitle')}" },
    { target: "Certificate ID: ", replacement: "t('profile.certsModalId')" },
    { target: "Issued To: ", replacement: "t('profile.certsModalIssuedTo')" },
    { target: "Certified Mitigated Carbon: ", replacement: "t('profile.certsModalEmissions')" },
    { target: "Verification Link: ", replacement: "t('profile.certsModalVerifyUrl')" },
    { target: "Print Certificate", replacement: "{t('profile.certsModalPrint')}" },
    { target: "Close", replacement: "{t('profile.certsModalClose')}" },
    { target: "Gamified Achievements", replacement: "{t('profile.achieveTitle')}" },
    { target: "Unlocked Achievements", replacement: "{t('profile.achieveUnlocked')}" },
    { target: "Unlocked: ", replacement: "t('profile.achieveDate')" },
    { target: "Ecological Reward Center", replacement: "{t('profile.rewardsTitle')}" },
    { target: "Total Points", replacement: "{t('profile.rewardsPoints')}" },
    { target: "Account Level: ", replacement: "t('profile.rewardsLevel')" },
    { target: " points until Level ", replacement: " + t('profile.rewardsPointsForNext') + " },
    { target: "Current Global Rank: ", replacement: "t('profile.rewardsCurrentRank')" },
    { target: "System Notification Logs", replacement: "{t('profile.notifsTitle')}" },
    { target: "No notifications found.", replacement: "{t('profile.notifsNoNotifs')}" },
    { target: "Platform Notification Preferences", replacement: "{t('profile.settingsTitle')}" },
    { target: "Weekly Carbon Digest Email", replacement: "{t('profile.settingsWeekly')}" },
    { target: "Goal Progress Alerts", replacement: "{t('profile.settingsGoals')}" },
    { target: "Badge Unlock Sound & Notifications", replacement: "{t('profile.settingsBadges')}" },
    { target: "Leaderboard Rankings Change Email", replacement: "{t('profile.settingsLeaderboard')}" },
    { target: "Interface Display Language", replacement: "{t('profile.settingsLanguage')}" },
    { target: "Preferred Currency", replacement: "{t('profile.settingsCurrency')}" },
    { target: "Distance Metrics Unit", replacement: "{t('profile.settingsDistance')}" },
    { target: "Security / Update Password", replacement: "{t('profile.settingsChangePassword')}" },
    { target: "label=\"Old Password\"", replacement: "label={t('profile.settingsOldPassword')}" },
    { target: "label=\"New Password\"", replacement: "label={t('profile.settingsNewPassword')}" },
    { target: "label=\"Confirm New Password\"", replacement: "label={t('profile.settingsConfirmPassword')}" },
    { target: "Update Account Password", replacement: "{t('profile.settingsUpdatePasswordBtn')}" },
    { target: "Password updated successfully!", replacement: "t('profile.passwordSuccess')" },
    { target: "Failed to update password. Please check your credentials.", replacement: "t('profile.passwordFail')" },
    { target: "New passwords do not match", replacement: "t('profile.passwordMatchError')" }
  ]
};

for (const [filename, fileRepls] of Object.entries(replacements)) {
  const filepath = path.join(pagesDir, filename);
  if (!fs.existsSync(filepath)) {
    console.log(`File not found: ${filename}`);
    continue;
  }
  let content = fs.readFileSync(filepath, 'utf8');
  
  // Apply all replacements
  let modified = false;
  for (const r of fileRepls) {
    if (content.includes(r.target)) {
      content = content.replace(new RegExp(escapeRegExp(r.target), 'g'), r.replacement);
      modified = true;
    }
  }
  
  if (modified) {
    fs.writeFileSync(filepath, content, 'utf8');
    console.log(`Successfully translated: ${filename}`);
  } else {
    console.log(`No changes made to: ${filename}`);
  }
}

function escapeRegExp(string) {
  return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); // $& means the whole matched string
}
console.log("Bulk page updates batch 2 completed!");
