const fs = require('fs');
const path = require('path');

const pagesDir = path.join(__dirname, 'frontend', 'src', 'pages');

const replacements = {
  "Dashboard.js": [
    // imports & hook
    { target: "const Dashboard = () => {", replacement: "const Dashboard = () => {\n  const { t } = useTranslation();" },
    { target: "import api from '../api';", replacement: "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';" },
    // strings
    { target: "Carbon Footprint Analytics", replacement: "{t('dashboard.analyticsTitle')}" },
    { target: "Advanced real-time tracking, benchmarking comparisons, and personalized sustainability tips.", replacement: "{t('dashboard.analyticsSubtitle')}" },
    { target: "Export CSV", replacement: "{t('dashboard.exportCSV')}" },
    { target: "Export PDF", replacement: "{t('dashboard.exportPDF')}" },
    { target: "label=\"Select Date Range Filter\"", replacement: "label={t('dashboard.selectDateRangeFilter')}" },
    { target: "<MenuItem value=\"today\">Today</MenuItem>", replacement: "<MenuItem value=\"today\">{t('dashboard.presetToday')}</MenuItem>" },
    { target: "<MenuItem value=\"yesterday\">Yesterday</MenuItem>", replacement: "<MenuItem value=\"yesterday\">{t('dashboard.presetYesterday')}</MenuItem>" },
    { target: "<MenuItem value=\"last-7\">Last 7 Days</MenuItem>", replacement: "<MenuItem value=\"last-7\">{t('dashboard.presetLast7')}</MenuItem>" },
    { target: "<MenuItem value=\"last-30\">Last 30 Days</MenuItem>", replacement: "<MenuItem value=\"last-30\">{t('dashboard.presetLast30')}</MenuItem>" },
    { target: "<MenuItem value=\"this-month\">This Month</MenuItem>", replacement: "<MenuItem value=\"this-month\">{t('dashboard.presetThisMonth')}</MenuItem>" },
    { target: "<MenuItem value=\"prev-month\">Previous Month</MenuItem>", replacement: "<MenuItem value=\"prev-month\">{t('dashboard.presetPrevMonth')}</MenuItem>" },
    { target: "<MenuItem value=\"custom\">Custom Date Range</MenuItem>", replacement: "<MenuItem value=\"custom\">{t('dashboard.presetCustom')}</MenuItem>" },
    { target: "label=\"From\"", replacement: "label={t('dashboard.from')}" },
    { target: "label=\"To\"", replacement: "label={t('dashboard.to')}" },
    { target: ">Search<", replacement: ">{t('dashboard.search')}<" },
    { target: "Period Emissions", replacement: "{t('dashboard.periodEmissions')}" },
    { target: "vs previous", replacement: "{t('dashboard.vsPrevious')}" },
    { target: "Daily Average", replacement: "{t('dashboard.dailyAverage')}" },
    { target: "logs tracked", replacement: "{t('dashboard.totalLogsTracked')}" },
    { target: "Peak/Min Days", replacement: "{t('dashboard.peakMinDays')}" },
    { target: "Max: ", replacement: "{t('dashboard.max')}: " },
    { target: "Min: ", replacement: "{t('dashboard.min')}: " },
    { target: "Period Eco Score", replacement: "{t('dashboard.periodEcoScore')}" },
    { target: "Percentile standing: ", replacement: "{t('dashboard.percentileStanding')}: " },
    { target: "Goal Completion %", replacement: "{t('dashboard.goalCompletion')}" },
    { target: "On track for 2026 targets", replacement: "{t('dashboard.activeTargets')}" },
    { target: "Monthly Carbon Savings", replacement: "{t('dashboard.monthlyCarbonSavings')}" },
    { target: "CO₂e reduced vs baseline", replacement: "{t('dashboard.carbonReductions')}" },
    { target: "Highest Category / Most Improved", replacement: "{t('dashboard.highestCategory')}" },
    { target: "High: Transport (48%)", replacement: "{t('dashboard.max') + ': Transport (48%)'}" },
    { target: "Improved: Food (-12%)", replacement: "{t('dashboard.mostImpact') + ': Food (-12%)'}" },
    { target: "Estimated Annual Footprint", replacement: "{t('dashboard.estimatedAnnualFootprint')}" },
    { target: "CO₂e annual projection", replacement: "{t('dashboard.basedOnLogs')}" },
    { target: "label=\"Emissions Trends\"", replacement: "label={t('dashboard.tabEmissionsOverTime')}" },
    { target: "label=\"Category Breakdown\"", replacement: "label={t('dashboard.tabCategoryBreakdown')}" },
    { target: "label=\"Personalized Recommendations\"", replacement: "label={t('dashboard.tabRecommendations')}" },
    { target: "label=\"Benchmarking & Insights\"", replacement: "label={t('dashboard.tabBenchmarking')}" },
    { target: "label=\"Recent Activity History\"", replacement: "label={t('dashboard.tabRecentLogs')}" },
    { target: "Daily Emissions Trend (Selected Period)", replacement: "{t('dashboard.chartDailyEmissions')}" },
    { target: "No activities logged in this range.", replacement: "{t('dashboard.noActivities')}" },
    { target: "Weekly Emissions Trend (All Time)", replacement: "{t('dashboard.chartWeeklyEmissions')}" },
    { target: "No summaries generated.", replacement: "{t('dashboard.noActivities')}" },
    { target: "Monthly Carbon Footprint Trend (All Time)", replacement: "{t('dashboard.chartMonthlyEmissions')}" },
    { target: "No monthly summaries generated.", replacement: "{t('dashboard.noActivities')}" },
    { target: "Donut Emission Breakdown (Selected Period)", replacement: "{t('dashboard.chartEmissionsDist')}" },
    { target: "Carbon Emissions Distribution", replacement: "{t('dashboard.chartEmissionsDist')}" },
    { target: "Emissions generated by your category choice", replacement: "{t('dashboard.emissionsByCategory')}" },
    { target: "How you compare to similar profiles", replacement: "{t('dashboard.howYouCompare')}" },
    { target: "Your Footprint", replacement: "{t('dashboard.yourFootprint')}" },
    { target: "Peer Average", replacement: "{t('dashboard.peerAverage')}" },
    { target: "National Target", replacement: "{t('dashboard.nationalTarget')}" },
    { target: "Benchmark Comparison (kg CO₂)", replacement: "{t('dashboard.chartBenchmarkComparison')}" },
    { target: "Sustainability Standing", replacement: "{t('dashboard.sustainabilityStanding')}" },
    { target: "You are doing great! Your carbon footprint is below the peer average.", replacement: "{t('dashboard.standingSummary')}" },
    { target: "Personalized Reduction recommendations", replacement: "{t('dashboard.personalizedRecs')}" },
    { target: "Tailored strategies based on your activity pattern to help you cut carbon.", replacement: "{t('dashboard.tailoredRecsSubtitle')}" },
    { target: "Estimated Savings", replacement: "{t('dashboard.estimatedSavings')}" },
    { target: "Status", replacement: "{t('dashboard.status')}" },
    { target: "Action", replacement: "{t('dashboard.action')}" },
    { target: "Implement", replacement: "{t('dashboard.implement')}" },
    { target: "COMPLETED", replacement: "{t('dashboard.completed')}" },
    { target: "ACTIVE", replacement: "{t('dashboard.active')}" },
    { target: "No recommendations found. Keep logging to get AI tips!", replacement: "{t('dashboard.noRecs')}" },
    { target: "Latest tracked carbon actions.", replacement: "{t('dashboard.latestTrackedActions')}" },
    { target: "Category", replacement: "{t('dashboard.activityCategory')}" },
    { target: "Activity Type", replacement: "{t('dashboard.activityType')}" },
    { target: "Quantity", replacement: "{t('dashboard.activityQuantity')}" },
    { target: "Emissions (kg)", replacement: "{t('dashboard.activityEmissions')}" },
    { target: "Date", replacement: "{t('dashboard.activityDate')}" },
    { target: "No activities logged for this period.", replacement: "{t('dashboard.noActivities')}" },
    { target: "Sign In Again", replacement: "{t('dashboard.signInAgain')}" },
    { target: "Your session token may have expired. Please re-authenticate to load your live analytics data.", replacement: "{t('dashboard.sessionExpiredAlert')}" }
  ],
  "ActivityLogging.js": [
    { target: "const ActivityLogging = () => {", replacement: "const ActivityLogging = () => {\n  const { t } = useTranslation();" },
    { target: "import api from '../api';", replacement: "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';" },
    { target: "Log Carbon Activity", replacement: "{t('activity.logTitle')}" },
    { target: "Track your daily transport, utility, and diet choices to compute your real-time carbon footprint.", replacement: "{t('activity.logSubtitle')}" },
    { target: "label=\"Category\"", replacement: "label={t('activity.category')}" },
    { target: "label=\"Activity Type\"", replacement: "label={t('activity.type')}" },
    { target: "label={`Quantity (${CATEGORIES[category].unit})`}", replacement: "label={`${t('activity.quantity')} (${CATEGORIES[category].unit})`}" },
    { target: "label=\"Date\"", replacement: "label={t('activity.date')}" },
    { target: "Cancel Edit", replacement: "{t('activity.cancelEdit')}" },
    { target: ">Update Log<", replacement: ">{t('activity.updateLog')}<" },
    { target: ">Log Activity<", replacement: ">{t('activity.logBtn')}<" },
    { target: "Activity log updated successfully!", replacement: "t('activity.updateSuccess')" },
    { target: "Activity logged successfully!", replacement: "t('activity.logSuccess')" },
    { target: "Activity log deleted successfully!", replacement: "t('activity.deleteSuccess')" },
    { target: "Quantity cannot be negative", replacement: "t('activity.negativeError')" },
    { target: "Logging action failed.", replacement: "t('activity.failedError')" },
    { target: "Could not retrieve activity logs.", replacement: "t('activity.retrieveError')" },
    { target: "Deletion failed.", replacement: "t('activity.deleteError')" },
    { target: "label=\"Filter by Date\"", replacement: "label={t('activity.filterByDate')}" },
    { target: "Reset Filter", replacement: "{t('activity.resetFilter')}" },
    { target: "Daily Summary", replacement: "{t('activity.dailySummary')}" },
    { target: "Total emissions for filtered date: ", replacement: "t('activity.totalEmissions')" },
    { target: "Recent Activity Logs (All-Time)", replacement: "{t('activity.recentLogsTitle')}" },
    { target: "Actions", replacement: "{t('activity.actions')}" },
    { target: "No activities logged yet.", replacement: "{t('activity.noLogs')}" },
    { target: "Are you sure you want to delete this activity log?", replacement: "t('activity.deleteConfirm')" }
  ],
  "Goals.js": [
    { target: "const Goals = () => {", replacement: "const Goals = () => {\n  const { t } = useTranslation();" },
    { target: "import api from '../api';", replacement: "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';" },
    { target: "Sustainability Goals", replacement: "{t('goals.title')}" },
    { target: "Establish Custom Sustainability Goal", replacement: "{t('goals.establishTitle')}" },
    { target: "label=\"Goal Title (e.g. 15% Commute Reduction)\"", replacement: "label={t('goals.formTitle')}" },
    { target: "label=\"Target Reduction (%)\"", replacement: "label={t('goals.formTarget')}" },
    { target: "label=\"Start Date\"", replacement: "label={t('goals.formStart')}" },
    { target: "label=\"Target End Date\"", replacement: "label={t('goals.formEnd')}" },
    { target: "Creating...", replacement: "{t('goals.formCreating')}" },
    { target: "Create Goal", replacement: "{t('goals.formSubmit')}" },
    { target: "Your Goals & Target Progress", replacement: "{t('goals.listTitle')}" },
    { target: "You don't have any active carbon reduction goals.", replacement: "{t('goals.noGoals')}" },
    { target: "Target: {goal.targetReductionPercentage}% Reduction", replacement: "t('goals.targetReduction') + goal.targetReductionPercentage + '% Reduction'" },
    { target: "Target: ", replacement: "t('goals.targetReduction')" },
    { target: "Reduction", replacement: "Reduction" },
    { target: " to ", replacement: " + t('goals.to') + " },
    { target: "Could not retrieve goals.", replacement: "t('goals.retrieveError')" },
    { target: "Goal established successfully!", replacement: "t('goals.successCreate')" },
    { target: "Failed to establish goal.", replacement: "t('goals.failCreate')" },
    { target: "Goal deleted successfully!", replacement: "t('goals.successDelete')" },
    { target: "Goal deletion failed.", replacement: "t('goals.failDelete')" },
    { target: "Target reduction percentage must be between 1% and 100%", replacement: "t('goals.validationTarget')" }
  ],
  "Recommendations.js": [
    { target: "const Recommendations = () => {", replacement: "const Recommendations = () => {\n  const { t } = useTranslation();" },
    { target: "import api from '../api';", replacement: "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';" },
    { target: "Personalized Eco Recommendations", replacement: "{t('recs.title')}" },
    { target: "We need a little more activity data to generate personalized recommendations. Log at least 3 activities to enable our smart engine.", replacement: "{t('recs.insufficientDataDesc')}" },
    { target: "Go To Activity Logs", replacement: "{t('recs.goToLogs')}" },
    { target: "AI-powered recommendations based on your activity pattern to help you cut carbon emissions.", replacement: "{t('recs.subtitle')}" },
    { target: "label=\"Active Recommendations\"", replacement: "label={t('recs.tabActive')}" },
    { target: "label=\"Recommendation History\"", replacement: "label={t('recs.tabHistory')}" },
    { target: "label=\"Recommendation Analytics\"", replacement: "label={t('recs.tabAnalytics')}" },
    { target: "label=\"Filter by Category\"", replacement: "label={t('recs.filterCategory')}" },
    { target: "<MenuItem value=\"ALL\">All Categories</MenuItem>", replacement: "<MenuItem value=\"ALL\">{t('recs.filterAll')}</MenuItem>" },
    { target: "<MenuItem value=\"TRANSPORT\">Transport</MenuItem>", replacement: "<MenuItem value=\"TRANSPORT\">{t('dashboard.catTransport')}</MenuItem>" },
    { target: "<MenuItem value=\"ELECTRICITY\">Electricity</MenuItem>", replacement: "<MenuItem value=\"ELECTRICITY\">{t('dashboard.catElectricity')}</MenuItem>" },
    { target: "<MenuItem value=\"FOOD\">Food</MenuItem>", replacement: "<MenuItem value=\"FOOD\">{t('dashboard.catFood')}</MenuItem>" },
    { target: "<MenuItem value=\"SHOPPING\">Shopping</MenuItem>", replacement: "<MenuItem value=\"SHOPPING\">{t('dashboard.catShopping')}</MenuItem>" },
    { target: "label=\"Analysis Period\"", replacement: "label={t('recs.periodLabel')}" },
    { target: "<MenuItem value=\"7DAYS\">Last 7 Days</MenuItem>", replacement: "<MenuItem value=\"7DAYS\">{t('recs.period7')}</MenuItem>" },
    { target: "<MenuItem value=\"30DAYS\">Last 30 Days</MenuItem>", replacement: "<MenuItem value=\"30DAYS\">{t('recs.period30')}</MenuItem>" },
    { target: "<MenuItem value=\"CUSTOM\">Custom Range</MenuItem>", replacement: "<MenuItem value=\"CUSTOM\">{t('recs.periodCustom')}</MenuItem>" },
    { target: "label=\"From\"", replacement: "label={t('recs.from')}" },
    { target: "label=\"To\"", replacement: "label={t('recs.to')}" },
    { target: ">Apply Filter<", replacement: ">{t('recs.search')}<" },
    { target: "Estimated Period Savings: ", replacement: "t('recs.estSavings')" },
    { target: "Active Recommendations: ", replacement: "t('recs.activeRecsCount')" },
    { target: "Completed Tasks: ", replacement: "t('recs.completedRecsCount')" },
    { target: "No active recommendations matching your filter.", replacement: "{t('recs.noActive')}" },
    { target: "CRITICAL", replacement: "t('recs.badgeCritical')" },
    { target: "HIGH", replacement: "t('recs.badgeHigh')" },
    { target: "MEDIUM", replacement: "t('recs.badgeMedium')" },
    { target: "LOW", replacement: "t('recs.badgeLow')" },
    { target: "Potential Savings: ", replacement: "t('recs.potentialSavings')" },
    { target: " kg CO2", replacement: "t('recs.kg')" },
    { target: "Implement Action", replacement: "{t('recs.actionImplement')}" },
    { target: "Ignore Recommendation", replacement: "{t('recs.actionIgnore')}" },
    { target: "Snooze (24h)", replacement: "{t('recs.actionSnooze')}" },
    { target: "View Details", replacement: "{t('recs.actionDetails')}" },
    { target: "No historical recommendations found.", replacement: "{t('recs.noHistory')}" },
    { target: "Re-activate", replacement: "{t('recs.actionReactivate')}" },
    { target: "Total Emissions Averted", replacement: "t('recs.totalAverted')" },
    { target: "Recommendation Implementation Rate", replacement: "t('recs.implementationRate')" },
    { target: "Estimated Carbon Savings by Category", replacement: "t('recs.categorySavingsTitle')" },
    { target: "Recommendation Status Distribution", replacement: "t('recs.statusDistribution')" },
    { target: "Not enough recommendation data to display charts.", replacement: "{t('recs.noDataAnalytics')}" },
    { target: "Recommendation Analysis Details", replacement: "{t('recs.dialogTitle')}" },
    { target: "Close", replacement: "{t('recs.dialogClose')}" },
    { target: "Potential Carbon Reduction: ", replacement: "t('recs.dialogPotential')" },
    { target: "Difficulty / Feasibility Level: ", replacement: "t('recs.dialogDifficulty')" },
    { target: "Estimated Implementation Cost: ", replacement: "t('recs.dialogCost')" },
    { target: "Target Mitigation Timeline: ", replacement: "t('recs.dialogTimeline')" },
    { target: "Why this recommendation is generated:", replacement: "{t('recs.dialogWhy')}" },
    { target: "Actionable Implementation Steps:", replacement: "{t('recs.dialogHow')}" },
    { target: "Could not retrieve personalized recommendations.", replacement: "t('recs.retrieveError')" },
    { target: "Failed to update recommendation status.", replacement: "t('recs.failUpdate')" }
  ],
  "Leaderboard.js": [
    { target: "const Leaderboard = () => {", replacement: "const Leaderboard = () => {\n  const { t } = useTranslation();" },
    { target: "import api from '../api';", replacement: "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';" },
    { target: "Community Leaderboard", replacement: "{t('leaderboard.title')}" },
    { target: "Monthly Emissions Ranking", replacement: "{t('leaderboard.subtitle')}" },
    { target: "No standings available.", replacement: "{t('leaderboard.noUsers')}" },
    { target: "Active Participant", replacement: "{t('leaderboard.activeParticipant')}" },
    { target: "kg CO2 logged", replacement: "{t('leaderboard.savings')}" },
    { target: "Your Earned Achievements", replacement: "{t('profile.tabAchievements')}" },
    { target: "No Badges Earned Yet", replacement: "{t('profile.badgesLocked')}" },
    { target: "Log daily activities and complete your target reduction goals to unlock community accomplishments!", replacement: "{t('profile.badgesLockedDesc')}" },
    { target: "Awarded: ", replacement: "t('profile.badgesEarnedOn')" },
    { target: "Could not retrieve leaderboard standings.", replacement: "t('leaderboard.retrieveError')" }
  ],
  "Feedback.js": [
    { target: "const Feedback = () => {", replacement: "const Feedback = () => {\n  const { t } = useTranslation();" },
    { target: "import api from '../api';", replacement: "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';" },
    { target: "Submit Platform Feedback", replacement: "{t('feedback.title')}" },
    { target: "Help us improve Carbon Tracker. Share your experience, report bugs, or request features.", replacement: "{t('feedback.subtitle')}" },
    { target: "label=\"Feedback Category\"", replacement: "label={t('feedback.formCategory')}" },
    { target: "label=\"Star Rating (1-5)\"", replacement: "label={t('feedback.formRating')}" },
    { target: "label=\"Written Feedback\"", replacement: "label={t('feedback.formText')}" },
    { target: "Submit Feedback", replacement: "{t('feedback.formSubmit')}" },
    { target: "Submitting...", replacement: "{t('feedback.submitting')}" },
    { target: "Feedback submitted successfully! Thank you for helping us improve.", replacement: "t('feedback.successMsg')" },
    { target: "Failed to submit feedback.", replacement: "t('feedback.errorMsg')" }
  ],
  "LoginPage.js": [
    { target: "const LoginPage = () => {", replacement: "const LoginPage = () => {\n  const { t } = useTranslation();" },
    { target: "import { useAuth } from '../context/AuthContext';", replacement: "import { useAuth } from '../context/AuthContext';\nimport { useTranslation } from '../context/LanguageContext';" },
    { target: "Measure, Reduce, and <Box component=\"span\" sx={{ color: 'primary.main' }}>Offset</Box> Your Footprint.", replacement: "{t('auth.loginHeroTitle')}" },
    { target: "Join thousands of community members logging their daily activities, competing on the leaderboard, and completing carbon reduction goals.", replacement: "{t('auth.loginHeroDesc')}" },
    { target: "TONS CO2 SAVED", replacement: "{t('auth.tonsSaved')}" },
    { target: "ACTIVITIES LOGGED", replacement: "{t('auth.activitiesLogged')}" },
    { target: "Sign in to manage your carbon footprint logs and tracker.", replacement: "{t('auth.loginSubtitle')}" },
    { target: "label=\"Email Address\"", replacement: "label={t('auth.email')}" },
    { target: "label=\"Password\"", replacement: "label={t('auth.password')}" },
    { target: "Forgot Password?", replacement: "{t('auth.forgot_password')}" },
    { target: "Signing in...", replacement: "{t('auth.loggingIn')}" },
    { target: "Sign In", replacement: "{t('auth.login')}" },
    { target: "<Divider>Or</Divider>", replacement: "<Divider>{t('auth.or')}</Divider>" },
    { target: "Sign In with Google", replacement: "{t('auth.googleLogin')}" },
    { target: "Don't have an account?", replacement: "{t('auth.noAccount')}" },
    { target: "Register here", replacement: "{t('auth.registerHere')}" }
  ],
  "RegisterPage.js": [
    { target: "const RegisterPage = () => {", replacement: "const RegisterPage = () => {\n  const { t } = useTranslation();" },
    { target: "import { useAuth } from '../context/AuthContext';", replacement: "import { useAuth } from '../context/AuthContext';\nimport { useTranslation } from '../context/LanguageContext';" },
    { target: "Start Your <Box component=\"span\" sx={{ color: 'primary.main' }}>Green</Box> Journey Today.", replacement: "{t('auth.registerHeroTitle')}" },
    { target: "Create your account to unlock personalized recommendations, track your sustainability logs, and visualize progress in real-time.", replacement: "{t('auth.registerHeroDesc')}" },
    { target: "Did you know?", replacement: "{t('auth.didYouKnow')}" },
    { target: "Logging activities daily helps build eco-conscious habits. Average users reduce their carbon output by 15% in their first month!", replacement: "{t('auth.didYouKnowDesc')}" },
    { target: "Join the carbon tracking platform and begin measuring impact.", replacement: "{t('auth.registerSubtitle')}" },
    { target: "label=\"Full Name\"", replacement: "label={t('auth.fullName')}" },
    { target: "label=\"Email Address\"", replacement: "label={t('auth.email')}" },
    { target: "label=\"Mobile Number\"", replacement: "label={t('auth.mobileNumber')}" },
    { target: "label=\"Password\"", replacement: "label={t('auth.password')}" },
    { target: "label=\"Confirm Password\"", replacement: "label={t('auth.confirmPassword')}" },
    { target: "Registering...", replacement: "{t('auth.registering')}" },
    { target: "Register", replacement: "{t('auth.register')}" },
    { target: "Already have an account?", replacement: "{t('auth.hasAccount')}" },
    { target: "Sign in here", replacement: "{t('auth.loginHere')}" },
    { target: "\"Password must be at least 8 characters long.\"", replacement: "t('auth.validationPasswordLength')" },
    { target: "\"Password must be alphanumeric (contain both letters and numbers).\"", replacement: "t('auth.validationPasswordAlphanumeric')" },
    { target: "\"Password must contain at least one special character (e.g. @, #, $, %, etc.).\"", replacement: "t('auth.validationPasswordSpecial')" },
    { target: "\"Passwords do not match\"", replacement: "t('profile.passwordMatchError')" },
    { target: "\"Registration completed! Redirecting to login...\"", replacement: "t('auth.registrationSuccess')" }
  ],
  "ForgotPasswordPage.js": [
    { target: "const ForgotPasswordPage = () => {", replacement: "const ForgotPasswordPage = () => {\n  const { t } = useTranslation();" },
    { target: "import api from '../api';", replacement: "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';" },
    { target: "Forgot Password", replacement: "{t('auth.forgotPasswordTitle')}" },
    { target: "Enter your registered email address to receive a 6-digit verification code.", replacement: "{t('auth.forgotPasswordSubtitle')}" },
    { target: "label=\"Email Address\"", replacement: "label={t('auth.email')}" },
    { target: "Sending OTP...", replacement: "{t('auth.forgotPasswordSending')}" },
    { target: "Send OTP", replacement: "{t('auth.forgotPasswordBtn')}" },
    { target: "Back to Sign In", replacement: "{t('auth.loginHere')}" }
  ],
  "OtpVerificationPage.js": [
    { target: "const OtpVerificationPage = () => {", replacement: "const OtpVerificationPage = () => {\n  const { t } = useTranslation();" },
    { target: "import api from '../api';", replacement: "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';" },
    { target: "Verify OTP", replacement: "{t('auth.otpTitle')}" },
    { target: "Enter the 6-digit code sent to <strong>{email}</strong>.", replacement: "<Box component=\"span\">{t('auth.otpSubtitle')} <strong>{email}</strong></Box>" },
    { target: "label=\"Email Address\"", replacement: "label={t('auth.email')}" },
    { target: "label=\"6-Digit OTP\"", replacement: "label={t('auth.otpLabel')}" },
    { target: "Verifying...", replacement: "{t('auth.otpsending')}" },
    { target: "Verify Code", replacement: "{t('auth.otpBtnVerify')}" },
    { target: "Resend OTP", replacement: "{t('auth.resendOtp')}" },
    { target: "Back to Sign In", replacement: "{t('auth.loginHere')}" }
  ],
  "ResetPasswordPage.js": [
    { target: "const ResetPasswordPage = () => {", replacement: "const ResetPasswordPage = () => {\n  const { t } = useTranslation();" },
    { target: "import api from '../api';", replacement: "import api from '../api';\nimport { useTranslation } from '../context/LanguageContext';" },
    { target: "Reset Password", replacement: "{t('auth.resetPasswordTitle')}" },
    { target: "Set your new account password.", replacement: "{t('auth.resetPasswordSubtitle')}" },
    { target: "label=\"New Password\"", replacement: "label={t('profile.settingsNewPassword')}" },
    { target: "label=\"Confirm Password\"", replacement: "label={t('auth.confirmPassword')}" },
    { target: "Updating Password...", replacement: "{t('auth.resetPasswordSending')}" },
    { target: "Reset Password", replacement: "{t('auth.resetPasswordBtn')}" },
    { target: "Back to Sign In", replacement: "{t('auth.loginHere')}" },
    { target: "'Passwords do not match'", replacement: "t('profile.passwordMatchError')" }
  ]
};

for (const [filename, fileRepls] of Object.entries(replacements)) {
  const filepath = path.join(pagesDir, filename);
  if (!fs.existsSync(filepath)) {
    console.log(`File not found: ${filename}`);
    continue;
  }
  let content = fs.readFileSync(filepath, 'utf8');
  
  // Apply all replacements
  let modified = false;
  for (const r of fileRepls) {
    if (content.includes(r.target)) {
      content = content.replace(new RegExp(escapeRegExp(r.target), 'g'), r.replacement);
      modified = true;
    }
  }
  
  if (modified) {
    fs.writeFileSync(filepath, content, 'utf8');
    console.log(`Successfully translated: ${filename}`);
  } else {
    console.log(`No changes made to: ${filename}`);
  }
}

function escapeRegExp(string) {
  return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); // $& means the whole matched string
}
console.log("Bulk page updates completed!");
