ALTER TABLE ai_conversations ADD COLUMN pinned BOOLEAN DEFAULT FALSE;
ALTER TABLE ai_conversations ADD COLUMN favorite BOOLEAN DEFAULT FALSE;

ALTER TABLE ai_messages ADD COLUMN liked BOOLEAN DEFAULT FALSE;
ALTER TABLE ai_messages ADD COLUMN disliked BOOLEAN DEFAULT FALSE;
