ALTER TABLE goals ADD COLUMN expected_progress DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE goals ADD COLUMN variance DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE goals ADD COLUMN track_status VARCHAR(255) DEFAULT 'ON_TRACK';
